//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AroFloSharp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactsZoneResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactsZoneResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AroFloSharp.Tests.Properties.ContactsZoneResources", typeof(ContactsZoneResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;status&quot;: &quot;0&quot;,
        ///  &quot;statusmessage&quot;: &quot;Login OK&quot;,
        ///  &quot;zoneresponse&quot;: {
        ///    &quot;contacts&quot;: [
        ///      {
        ///        &quot;surname&quot;: &quot;Accounts&quot;,
        ///        &quot;org&quot;: {
        ///          &quot;orgid&quot;: &quot;JCdKUyxQICAgCg==&quot;,
        ///          &quot;orgname&quot;: &quot;Myer&quot;
        ///        },
        ///        &quot;phone&quot;: &quot;&quot;,
        ///        &quot;contacttype&quot;: &quot;client&quot;,
        ///        &quot;email&quot;: &quot;&quot;,
        ///        &quot;email2&quot;: &quot;&quot;,
        ///        &quot;customfields&quot;: [],
        ///        &quot;notes&quot;: [],
        ///        &quot;givennames&quot;: &quot;Accounts&quot;,
        ///        &quot;documentsandphotos&quot;: [],
        ///        &quot;accesstype&quot;: &quot;Base&quot;,
        ///        &quot;userid&quot;: &quot;JCQ6XyJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContactsResponseJson {
            get {
                return ResourceManager.GetString("ContactsResponseJson", resourceCulture);
            }
        }
    }
}
