//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AroFloSharp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocationsZoneResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationsZoneResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AroFloSharp.Tests.Properties.LocationsZoneResources", typeof(LocationsZoneResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;status&quot;: &quot;0&quot;,
        ///  &quot;statusmessage&quot;: &quot;Login OK&quot;,
        ///  &quot;zoneresponse&quot;: {
        ///    &quot;locations&quot;: [
        ///      {
        ///        &quot;locationid&quot;: &quot;JSc6QyVRXFwgCg==&quot;,
        ///        &quot;gpslat&quot;: &quot;0&quot;,
        ///        &quot;postcode&quot;: &quot;2000&quot;,
        ///        &quot;SiteContact&quot;: &quot;&quot;,
        ///        &quot;state&quot;: &quot;NSW&quot;,
        ///        &quot;suburb&quot;: &quot;Port of Sydney&quot;,
        ///        &quot;SiteEmail&quot;: &quot;&quot;,
        ///        &quot;customfields&quot;: [{
        ///            &quot;fieldid&quot;: &quot;JCZaVyVQUCAgCg==&quot;,
        ///            &quot;value&quot;: &quot;Word of Mouth&quot;,
        ///            &quot;archived&quot;: &quot;false&quot;,
        ///            &quot;type&quot;: &quot;Select&quot;,
        ///            &quot;name&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocationsZoneJsonResponse {
            get {
                return ResourceManager.GetString("LocationsZoneJsonResponse", resourceCulture);
            }
        }
    }
}
