//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AroFloSharp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuotesZoneResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuotesZoneResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AroFloSharp.Tests.Properties.QuotesZoneResources", typeof(QuotesZoneResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;zoneresponse&quot;:{&quot;maxpageresults&quot;:&quot;500&quot;,&quot;pagenumber&quot;:&quot;1&quot;,&quot;queryresponsetimes&quot;:{&quot;documentsandphotos&quot;:7,&quot;quotes&quot;:80},&quot;quotes&quot;:[{&quot;totalprofitmarginpercent&quot;:&quot;9.09&quot;,&quot;approveddate&quot;:&quot;&quot;,&quot;estimator&quot;:{},&quot;lines&quot;:[{&quot;worktypevalue&quot;:&quot;0.0000&quot;,&quot;worktype&quot;:&quot;&quot;,&quot;totalinc&quot;:&quot;203.28&quot;,&quot;optiongroupname&quot;:&quot;&quot;,&quot;itemtype&quot;:&quot;Material&quot;,&quot;partno&quot;:&quot;Assembly&quot;,&quot;isapproved&quot;:&quot;true&quot;,&quot;totalex&quot;:&quot;184.80&quot;,&quot;labourunitrate&quot;:&quot;0.2500&quot;,&quot;item&quot;:&quot;Electrical - Double GPO install&quot;,&quot;cost&quot;:&quot;8.4000&quot;,&quot;parentlineid&quot;:&quot;&quot;,&quot;sell&quot;:&quot;9.2400&quot;,&quot;labourtotal&quot;:&quot;320.00&quot;,&quot;lineid&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZoneResponse_Join_Lines_Notes_Project_DocandPhotos {
            get {
                return ResourceManager.GetString("ZoneResponse_Join_Lines_Notes_Project_DocandPhotos", resourceCulture);
            }
        }
    }
}
